[solar]
format = 2

[project]
name = "sapho-cmm"
language = "cmm"
default_test = "generated"
default_profile = "debug"

[compiler]
backend = "yanc"
source = "software/processor.cmm"
processor = "sapho_demo"
frequency_mhz = 100
simulation_clocks = 100000

[yanc]
diagnostics = "pt"

[simulation]
backend = "iverilog"

[synthesis]
backend = "yosys"
top = "sapho_demo"

[[profile]]
name = "debug"
defines = ["YANC_DEBUG"]
